language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - 7.1
  - 7.2
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm # https://github.com/php-vcr/php-vcr/issues/90

dist: trusty
sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer self-update -q
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - composer install --no-interaction --prefer-dist

script:
  - mkdir -p build/logs
  - composer test-coverage

after_script:
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: false
  webhooks:
    - http://helit.org:8093/+sujevo-dev/showSuccessfulBuildMessages=always
